server:
  address: 0.0.0.0
  port: ${SERVER_PORT:2333}

lavalink:
  server:
    password: ${LAVALINK_SERVER_PASSWORD:localpass}
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 1200
    frameBufferDurationMs: 5000
    gc-warnings: true

logging:
  level:
    root: INFO
